### ISSUE TITLE
[Bug-Candidate]: Unresolved reference to identifier _counters.slot in Seaport 1.5

### ISSUE THREAD

**Issue by izcoser** [crytic/slither#2157] opened 2023-10-05 18:49 UTC
### Describe the issue:

Slither fails when analyzing Seaport 1.5 (0x00000000000000adc04c56bf30ac9d3c0aaf14dc).

### Code example to reproduce the issue:

` slither 0x00000000000000adc04c56bf30ac9d3c0aaf14dc
`

### Version:

0.9.6

### Relevant log output:

```shell
(slither_venv) [izcoser@pcvm ~]$ slither 0x00000000000000adc04c56bf30ac9d3c0aaf14dc
'solc --standard-json --allow-paths /home/izcoser/crytic-export/etherscan-contracts/0x00000000000000adc04c56bf30ac9d3c0aaf14dc-Seaport' running
Traceback (most recent call last):
  File "/home/izcoser/slither_venv/lib/python3.11/site-packages/slither/__main__.py", line 814, in main_impl
    ) = process_all(filename, args, detector_classes, printer_classes)
        ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/izcoser/slither_venv/lib/python3.11/site-packages/slither/__main__.py", line 102, in process_all
    ) = process_single(compilation, args, detector_classes, printer_classes)
        ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/izcoser/slither_venv/lib/python3.11/site-packages/slither/__main__.py", line 80, in process_single
    slither = Slither(target, ast_format=ast, **vars(args))
              ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/izcoser/slither_venv/lib/python3.11/site-packages/slither/slither.py", line 135, in __init__
    self._init_parsing_and_analyses(kwargs.get("skip_analyze", False))
  File "/home/izcoser/slither_venv/lib/python3.11/site-packages/slither/slither.py", line 145, in _init_parsing_and_analyses
    raise e
  File "/home/izcoser/slither_venv/lib/python3.11/site-packages/slither/slither.py", line 141, in _init_parsing_and_analyses
    parser.parse_contracts()
  File "/home/izcoser/slither_venv/lib/python3.11/site-packages/slither/solc_parsing/slither_compilation_unit_solc.py", line 531, in parse_contracts
    self._analyze_third_part(contracts_to_be_analyzed, libraries)
  File "/home/izcoser/slither_venv/lib/python3.11/site-packages/slither/solc_parsing/slither_compilation_unit_solc.py", line 641, in _analyze_third_part
    self._analyze_variables_modifiers_functions(contract)
  File "/home/izcoser/slither_venv/lib/python3.11/site-packages/slither/solc_parsing/slither_compilation_unit_solc.py", line 740, in _analyze_variables_modifiers_functions
    contract.analyze_content_functions()
  File "/home/izcoser/slither_venv/lib/python3.11/site-packages/slither/solc_parsing/declarations/contract.py", line 424, in analyze_content_functions
    function_parser.analyze_content()
  File "/home/izcoser/slither_venv/lib/python3.11/site-packages/slither/solc_parsing/declarations/function.py", line 312, in analyze_content
    yul_parser.analyze_expressions()
  File "/home/izcoser/slither_venv/lib/python3.11/site-packages/slither/solc_parsing/yul/parse_yul.py", line 342, in analyze_expressions
    node.analyze_expressions()
  File "/home/izcoser/slither_venv/lib/python3.11/site-packages/slither/solc_parsing/yul/parse_yul.py", line 65, in analyze_expressions
    expression = parse_yul(self._scope, self, self._unparsed_expression)
                 ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/izcoser/slither_venv/lib/python3.11/site-packages/slither/solc_parsing/yul/parse_yul.py", line 885, in parse_yul
    op: Expression = parsers.get(ast["nodeType"], parse_yul_unsupported)(root, node, ast)
                     ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/izcoser/slither_venv/lib/python3.11/site-packages/slither/solc_parsing/yul/parse_yul.py", line 711, in parse_yul_function_call
    args = [parse_yul(root, node, arg) for arg in ast["arguments"]]
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/izcoser/slither_venv/lib/python3.11/site-packages/slither/solc_parsing/yul/parse_yul.py", line 711, in <listcomp>
    args = [parse_yul(root, node, arg) for arg in ast["arguments"]]
            ^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/izcoser/slither_venv/lib/python3.11/site-packages/slither/solc_parsing/yul/parse_yul.py", line 885, in parse_yul
    op: Expression = parsers.get(ast["nodeType"], parse_yul_unsupported)(root, node, ast)
                     ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/izcoser/slither_venv/lib/python3.11/site-packages/slither/solc_parsing/yul/parse_yul.py", line 847, in parse_yul_identifier
    raise SlitherException(f"unresolved reference to identifier {name}")
slither.exceptions.SlitherException: unresolved reference to identifier _counters.slot
ERROR:root:Error:
ERROR:root:unresolved reference to identifier _counters.slot
ERROR:root:Please report an issue to https://github.com/crytic/slither/issues
```

**Comment by 0xalpharush** [comment] 2023-10-06 00:59
Thanks for reporting this issue. For tracking purposes, this is a duplicate of https://github.com/crytic/slither/issues/1654

**Comment by 0xalpharush** [comment] 2023-10-17 13:35
Closed by https://github.com/crytic/slither/pull/2168

**Closed by 0xalpharush** 2023-10-17 13:35 UTC
Labels: duplicate, bug-candidate
