### ISSUE TITLE
Source mapping for lines are not always correct

### ISSUE THREAD

**Issue by defunctio** [crytic/slither#180] opened 2019-02-25 17:51 UTC
The line numbers for issues reported by slither often don't line up to the source lines indicated. I don't have any public examples but it should be relatively easy to reproduce. I noticed when reviewing a contract with a lot of `Conformance to Solidity naming conventions` issues.

**Comment by Xenomega** [comment] 2019-02-25 17:54
More information that likely addresses the cause of this issue:
- If you're relying on line numbers solidity gives you, Solidity strips certain types of whitespacing before it processes a file, so its line numbers are off (or something to that effect, I encountered this when working on unrelated tooling before). 
- The offset + length numbers it gives you to address the data in the file are correct, so you can deduce correct line numbers yourself.

**Comment by montyly** [comment] 2019-04-01 10:19
Fixed with #194

**Closed by montyly** 2019-04-01 10:19 UTC
Labels: High Priority, bug
