### ISSUE TITLE
uninitialized-local reports false positives for structs

### ISSUE THREAD

**Issue by snd** [crytic/slither#779] opened 2021-01-25 22:55 UTC
given `StructType` a common pattern is:

```solidity
StructType memory structVar;
structVar.a = 1;
structVar.b = "a";
```

slither reports `uninitialized-local` for `StructType memory structVar` in this case.

a useful addition would be to check for each struct field whether it is assigned below before it is read.

alternatively this detector could detect that locals (and storage variables) are initialized before they are read instead of checking that they are initialized in the line they are defined.
this should result in catching all dangerous unintended reads from uninitialized variables while producing less noise.
when handling structs it could treat each field separately.

the same could be done for `uninitialized-state`.

**Comment by montyly** [comment] 2021-02-01 07:51
Duplicate of https://github.com/crytic/slither/issues/365

**Closed by montyly** 2021-02-01 07:51 UTC
