### ISSUE TITLE
[Bug]: State variables shadowed by a local variable are incorrectly set to the local variable 

### ISSUE THREAD

**Issue by Tiko7454** [crytic/slither#2058] opened 2023-07-19 08:21 UTC
### Describe the issue:

A state variable is used before it was shadowed. The dependency goes to the local variable instead of state variable

### Code example to reproduce the issue:

```solidity
// SPDX-License-Identifier: UNLICENSED

pragma solidity 0.8.7;

contract B {
    uint public x = 21;
    function a()  public {
        uint u = 2 * x;  // BUG
        uint x;
    }
}
```

```python
> from slither import Slither
>
>
> a = Slither('b.sol').contracts[0].functions[0]
> buggy_node = a.nodes[1]
> print(buggy_node.variables_read[0].canonical_name)
>> B.a().x
```

### Version:

0.9.3
(tested the freshest dev branch 3e390264a4903c522718b33478e5acb735f3e0e6)

**Comment by smonicas** [comment] 2023-07-19 15:28
The issue is in early expression parsing because `x` is found by this code as the local variable. Removing this code makes the example works however it will fail if the legacy ast is used and i'm not sure if there are other edge cases that require it.
https://github.com/crytic/slither/blob/e5f2a86f0906fd62c6c4eccb9dbfa5ab30671a78/slither/solc_parsing/expressions/find_variable.py#L83-L86

**Comment by 0xalpharush** [comment] 2023-10-12 19:08
Closed by https://github.com/crytic/slither/pull/2121

**Closed by 0xalpharush** 2023-10-12 19:08 UTC
Labels: bug, parsing
