### ISSUE TITLE
KeyError: 'value' while parsing contracts.

### ISSUE THREAD

**Issue by sobolev-igor** [crytic/slither#668] opened 2020-10-16 10:22 UTC
I'm having an issue while scanning my project (https://github.com/zeriontech/defi-sdk/tree/interactive, `interactive` branch). As I see, the parser fails, this may be because of the latest Solidity syntax.
Hope you could help me!

Here is a traceback:

```
Traceback (most recent call last):
  File "/usr/local/lib/python3.8/site-packages/slither/__main__.py", line 692, in main_impl
    ) = process_all(filename, args, detector_classes, printer_classes)
  File "/usr/local/lib/python3.8/site-packages/slither/__main__.py", line 79, in process_all
    ) = process_single(compilation, args, detector_classes, printer_classes)
  File "/usr/local/lib/python3.8/site-packages/slither/__main__.py", line 62, in process_single
    slither = Slither(target, ast_format=ast, **vars(args))
  File "/usr/local/lib/python3.8/site-packages/slither/slither.py", line 100, in __init__
    self._parser.analyze_contracts()
  File "/usr/local/lib/python3.8/site-packages/slither/solc_parsing/slitherSolc.py", line 338, in analyze_contracts
    self._analyze_first_part(contracts_to_be_analyzed, libraries)
  File "/usr/local/lib/python3.8/site-packages/slither/solc_parsing/slitherSolc.py", line 395, in _analyze_first_part
    self._parse_struct_var_modifiers_functions(contract)
  File "/usr/local/lib/python3.8/site-packages/slither/solc_parsing/slitherSolc.py", line 461, in _parse_struct_var_modifiers_functions
    contract.parse_state_variables()
  File "/usr/local/lib/python3.8/site-packages/slither/solc_parsing/declarations/contract.py", line 303, in parse_state_variables
    var_parser = StateVariableSolc(var, varNotParsed)
  File "/usr/local/lib/python3.8/site-packages/slither/solc_parsing/variables/state_variable.py", line 9, in __init__
    super().__init__(variable, variable_data)
  File "/usr/local/lib/python3.8/site-packages/slither/solc_parsing/variables/variable_declaration.py", line 65, in __init__
    self._init_from_declaration(variable_data, variable_data["value"])
KeyError: 'value'
ERROR:root:None
ERROR:root:Error in .
ERROR:root:Traceback (most recent call last):
  File "/usr/local/lib/python3.8/site-packages/slither/__main__.py", line 692, in main_impl
    ) = process_all(filename, args, detector_classes, printer_classes)
  File "/usr/local/lib/python3.8/site-packages/slither/__main__.py", line 79, in process_all
    ) = process_single(compilation, args, detector_classes, printer_classes)
  File "/usr/local/lib/python3.8/site-packages/slither/__main__.py", line 62, in process_single
    slither = Slither(target, ast_format=ast, **vars(args))
  File "/usr/local/lib/python3.8/site-packages/slither/slither.py", line 100, in __init__
    self._parser.analyze_contracts()
  File "/usr/local/lib/python3.8/site-packages/slither/solc_parsing/slitherSolc.py", line 338, in analyze_contracts
    self._analyze_first_part(contracts_to_be_analyzed, libraries)
  File "/usr/local/lib/python3.8/site-packages/slither/solc_parsing/slitherSolc.py", line 395, in _analyze_first_part
    self._parse_struct_var_modifiers_functions(contract)
  File "/usr/local/lib/python3.8/site-packages/slither/solc_parsing/slitherSolc.py", line 461, in _parse_struct_var_modifiers_functions
    contract.parse_state_variables()
  File "/usr/local/lib/python3.8/site-packages/slither/solc_parsing/declarations/contract.py", line 303, in parse_state_variables
    var_parser = StateVariableSolc(var, varNotParsed)
  File "/usr/local/lib/python3.8/site-packages/slither/solc_parsing/variables/state_variable.py", line 9, in __init__
    super().__init__(variable, variable_data)
  File "/usr/local/lib/python3.8/site-packages/slither/solc_parsing/variables/variable_declaration.py", line 65, in __init__
    self._init_from_declaration(variable_data, variable_data["value"])
KeyError: 'value'

```

**Comment by montyly** [comment] 2020-10-17 06:48
Hi @sobolev-igor ,

Thank you for your interest in Slither. I think the issue comes from the use of contracts with duplicate names. See the truffle warnings:
```
> Duplicate contract names found for Hydro.
> This can cause errors and unknown behavior. Please rename one of your contracts.

> Duplicate contract names found for Hydro.
> This can cause errors and unknown behavior. Please rename one of your contracts.

> Duplicate contract names found for Hydro.
> This can cause errors and unknown behavior. Please rename one of your contracts.

> Duplicate contract names found for BasePool.
> This can cause errors and unknown behavior. Please rename one of your contracts.

> Duplicate contract names found for SynthetixAssetAdapter.
> This can cause errors and unknown behavior. Please rename one of your contracts.

> Duplicate contract names found for DssCdpManager.
> This can cause errors and unknown behavior. Please rename one of your contracts.

> Duplicate contract names found for Jug.
> This can cause errors and unknown behavior. Please rename one of your contracts.

> Duplicate contract names found for Pot.
> This can cause errors and unknown behavior. Please rename one of your contracts.

> Duplicate contract names found for Proxy.
> This can cause errors and unknown behavior. Please rename one of your contracts.

> Duplicate contract names found for Synthetix.
> This can cause errors and unknown behavior. Please rename one of your contracts.

> Duplicate contract names found for Vat.
> This can cause errors and unknown behavior. Please rename one of your contracts.
```

A codebase that contains contracts with duplicate names prevents truffle form generating correct compilation artifact, which prevent also Slither's analysis.

**Comment by sobolev-igor** [comment] 2020-10-17 18:43
Thanks @montyly ! I'll give it a try!

**Comment by sobolev-igor** [comment] 2020-10-17 21:00
I've [fixed](https://github.com/zeriontech/defi-sdk/tree/4a0cd9f0ad222cb949b5e12069dd6ad03b5e1e05) all the truffle warnings, but the issue still persists... can it be connected to the newest Solidity syntax? I use structs in a separate file, `immutable` keyword and new syntax for gas and value: `{gas: , value: }`.

If it's a Truffle issue, I can try to use slither with solc, but currently `slither ./contracts/core/Ownable.sol` does not work, too. May be it can be connected to 0.7.x solc output?

**Comment by maxgrok** [comment] 2020-10-21 16:43
I'm coming up against a similar error and not getting any warnings from Truffle. 

slither contracts/LexToken.sol
Traceback (most recent call last):
  File "/usr/local/lib/python3.7/site-packages/slither/__main__.py", line 692, in main_impl
    ) = process_all(filename, args, detector_classes, printer_classes)
  File "/usr/local/lib/python3.7/site-packages/slither/__main__.py", line 79, in process_all
    ) = process_single(compilation, args, detector_classes, printer_classes)
  File "/usr/local/lib/python3.7/site-packages/slither/__main__.py", line 62, in process_single
    slither = Slither(target, ast_format=ast, **vars(args))
  File "/usr/local/lib/python3.7/site-packages/slither/slither.py", line 100, in __init__
    self._parser.analyze_contracts()
  File "/usr/local/lib/python3.7/site-packages/slither/solc_parsing/slitherSolc.py", line 338, in analyze_contracts
    self._analyze_first_part(contracts_to_be_analyzed, libraries)
  File "/usr/local/lib/python3.7/site-packages/slither/solc_parsing/slitherSolc.py", line 395, in _analyze_first_part
    self._parse_struct_var_modifiers_functions(contract)
  File "/usr/local/lib/python3.7/site-packages/slither/solc_parsing/slitherSolc.py", line 461, in _parse_struct_var_modifiers_functions
    contract.parse_state_variables()
  File "/usr/local/lib/python3.7/site-packages/slither/solc_parsing/declarations/contract.py", line 303, in parse_state_variables
    var_parser = StateVariableSolc(var, varNotParsed)
  File "/usr/local/lib/python3.7/site-packages/slither/solc_parsing/variables/state_variable.py", line 9, in __init__
    super().__init__(variable, variable_data)
  File "/usr/local/lib/python3.7/site-packages/slither/solc_parsing/variables/variable_declaration.py", line 65, in __init__
    self._init_from_declaration(variable_data, variable_data["value"])
KeyError: 'value'
ERROR:root:None
ERROR:root:Error in contracts/LexToken.sol
ERROR:root:Traceback (most recent call last):
  File "/usr/local/lib/python3.7/site-packages/slither/__main__.py", line 692, in main_impl
    ) = process_all(filename, args, detector_classes, printer_classes)
  File "/usr/local/lib/python3.7/site-packages/slither/__main__.py", line 79, in process_all
    ) = process_single(compilation, args, detector_classes, printer_classes)
  File "/usr/local/lib/python3.7/site-packages/slither/__main__.py", line 62, in process_single
    slither = Slither(target, ast_format=ast, **vars(args))
  File "/usr/local/lib/python3.7/site-packages/slither/slither.py", line 100, in __init__
    self._parser.analyze_contracts()
  File "/usr/local/lib/python3.7/site-packages/slither/solc_parsing/slitherSolc.py", line 338, in analyze_contracts
    self._analyze_first_part(contracts_to_be_analyzed, libraries)
  File "/usr/local/lib/python3.7/site-packages/slither/solc_parsing/slitherSolc.py", line 395, in _analyze_first_part
    self._parse_struct_var_modifiers_functions(contract)
  File "/usr/local/lib/python3.7/site-packages/slither/solc_parsing/slitherSolc.py", line 461, in _parse_struct_var_modifiers_functions
    contract.parse_state_variables()
  File "/usr/local/lib/python3.7/site-packages/slither/solc_parsing/declarations/contract.py", line 303, in parse_state_variables
    var_parser = StateVariableSolc(var, varNotParsed)
  File "/usr/local/lib/python3.7/site-packages/slither/solc_parsing/variables/state_variable.py", line 9, in __init__
    super().__init__(variable, variable_data)
  File "/usr/local/lib/python3.7/site-packages/slither/solc_parsing/variables/variable_declaration.py", line 65, in __init__
    self._init_from_declaration(variable_data, variable_data["value"])
KeyError: 'value'

**Comment by shannonwells** [comment] 2020-10-22 22:08
I"m seeing this same error. Definitely not due to duplicate contracts. No additional other output.  Our project is compiling successfully with no warnings, and tests can run.  It might be due to a problem fetching solc versions. As you can see, the rest of the error is the same as above:
```
> Compiled successfully using:
   - solc: 0.7.3+commit.9bfce1f6.Emscripten.clang

- Fetching solc version list from solc-bin. Attempt #1

Traceback (most recent call last):
  File "/usr/local/lib/python3.8/site-packages/slither/__main__.py", line 692, in main_impl
    ) = process_all(filename, args, detector_classes, printer_classes)
  File "/usr/local/lib/python3.8/site-packages/slither/__main__.py", line 79, in process_all
    ) = process_single(compilation, args, detector_classes, printer_classes)
  File "/usr/local/lib/python3.8/site-packages/slither/__main__.py", line 62, in process_single
    slither = Slither(target, ast_format=ast, **vars(args))
  File "/usr/local/lib/python3.8/site-packages/slither/slither.py", line 100, in __init__
    self._parser.analyze_contracts()
  File "/usr/local/lib/python3.8/site-packages/slither/solc_parsing/slitherSolc.py", line 338, in analyze_contracts
    self._analyze_first_part(contracts_to_be_analyzed, libraries)
  File "/usr/local/lib/python3.8/site-packages/slither/solc_parsing/slitherSolc.py", line 395, in _analyze_first_part
    self._parse_struct_var_modifiers_functions(contract)
  File "/usr/local/lib/python3.8/site-packages/slither/solc_parsing/slitherSolc.py", line 461, in _parse_struct_var_modifiers_functions
    contract.parse_state_variables()
  File "/usr/local/lib/python3.8/site-packages/slither/solc_parsing/declarations/contract.py", line 303, in parse_state_variables
    var_parser = StateVariableSolc(var, varNotParsed)
  File "/usr/local/lib/python3.8/site-packages/slither/solc_parsing/variables/state_variable.py", line 9, in __init__
    super().__init__(variable, variable_data)
  File "/usr/local/lib/python3.8/site-packages/slither/solc_parsing/variables/variable_declaration.py", line 65, in __init__
    self._init_from_declaration(variable_data, variable_data["value"])
KeyError: 'value'
ERROR:root:None
ERROR:root:Error in .
```

**Comment by montyly** [comment] 2020-10-26 07:44
Hi @sobolev-igor. 

I was able to reproduce the bug. I believe the crash is coming from another truffe bug: it does not generate json artifacts for top-level structure and enum (https://github.com/trufflesuite/truffle/issues/3124), as a result, Slither can't found them. For example [`Basset`](https://github.com/zeriontech/defi-sdk/blob/29ee7ed5ae07819566aa7635925b757b8c12b640/contracts/interfaces/BasketManager.sol#L26-L33), or all the structures in [Structs.sol](https://github.com/zeriontech/defi-sdk/blob/interactive/contracts/shared/Structs.sol).


@maxgrok and @shannonwells: could you share the codebase where these bugs happen? We recently fixed many `KeyError` issues (https://github.com/crytic/slither/pull/642), these fixes will be available on the upcoming Slither's release.

**Comment by sobolev-igor** [comment] 2020-10-26 08:25
Hi, @montyly!

If the problem is in Truffle, how can I use Slither without Truffle?

**Comment by montyly** [comment] 2020-10-26 08:48
You can run slither directly on a Solidity file, ex:
```
slither contracts/core/TokenAdapterManager.sol
```

You need slither@master, as slither on pip (0.6.13) does not include https://github.com/crytic/slither/pull/642. This will be fixed with the upcoming new release (0.6.14), which will be out this week or the next one.

I have noticed that slither throws some internal warnings on the top-level structure that I will investigate, but in the meantime, the detectors work.

You can use [`solc-select`](https://github.com/crytic/solc-select) if you need to switch to a specific solc version (0.7.3 here).

Finally, if some files import files outside of `contracts` (ex: OZ dependencies), you will need to provide the [`--allow-paths`](https://solidity.readthedocs.io/en/v0.7.3/using-the-compiler.html?highlight=--allow-paths#using-the-commandline-compiler) flag to solc (ex: `--solc-args "--allow-paths nodes_modules/path/to/dep"`

**Comment by sobolev-igor** [comment] 2020-10-26 10:49
Thanks! slither@master seems to be working.

**Comment by shannonwells** [comment] 2020-10-26 14:56
@montyly 
>could you share the codebase where these bugs happen?
Sorry, I can't. It's a private repo.  I'll try master rather than the pip install.

**Comment by AlbertSu123** [comment] 2020-11-10 04:12
Are there any updates for when 0.6.14 will come out? If there are any simply pull requests a complete newcomer to slither can help with, just point me to them!

**Comment by montyly** [comment] 2020-11-10 09:34
Hi @AlbertSu123. I was aiming for last week, but unfortunately got delayed. You can see the progress here: https://github.com/crytic/slither/issues/676

0.6.14 is almost ready, and will be released this week.

**Closed** 2022-06-24 02:04 UTC
