### ISSUE TITLE
[Bug-Candidate]: Slither 

### ISSUE THREAD

**Issue by agentjacker** [crytic/slither#1413] opened 2022-10-07 00:10 UTC
### Describe the issue:

when i run .\slither . i get this 
<img width="729" alt="image" src="https://user-images.githubusercontent.com/114850373/194439731-721d161e-11c3-44ba-baea-285d39dc01b7.png">
<img width="736" alt="image" src="https://user-images.githubusercontent.com/114850373/194440044-73b354f2-602c-4d14-ac4c-cf4134ccc856.png">

i have already done the prerequisites and can do .\slither --help . how can i run slither to do a test on the smart contract. also do i have to cd in to the location of the smart contract. 

### Code example to reproduce the issue:

.\slither .

### Version:

0.9.0

**Comment by elopez** [comment] 2022-10-07 00:32
Hi! Yes, you should `cd` to the location of your project and then run `slither .`

You should also be able to run `slither C:\foo\bar\target` from anywhere, where `C:\foo\bar\yourproject` is your project folder.

**Comment by agentjacker** [comment] 2022-10-07 00:43
just did that but it didnt work
<img width="557" alt="image" src="https://user-images.githubusercontent.com/114850373/194442847-51b0a041-f067-4295-9007-f029367f2363.png">

**Comment by elopez** [comment] 2022-10-07 01:37
slither is not being found, so it sounds like your python's "Scripts" directory is not in PATH or you did not install slither yet, check my message here: https://github.com/crytic/slither/issues/1412#issuecomment-1270837671

**Comment by elopez** [comment] 2022-10-08 12:01
Closing as duplicate of #1415

**Closed by elopez** 2022-10-08 12:01 UTC
Labels: bug-candidate
