### ISSUE TITLE
[Bug-Candidate]: Incorrect type propagation from NewArray 

### ISSUE THREAD

**Issue by kevinclancy** [crytic/slither#1908] opened 2023-05-12 19:22 UTC
### Describe the issue:

In NewArray, the type of the array's elements is stored in a field called `array_type`.  In propagate_type in `convert.py`sets the lvalue's type using `ir.lvalue.set_type(ir.array_type)`. This sets the lvalues type to the type of the array's elements instead of the type of the array itself.

Suggested solution:
Rename the `array_type` field to `element_type`. Change the `NewArray` case in `propagate_types` to `ir.lvalue.set_type(ArrayType(ir.element_type, None))`.

### Code example to reproduce the issue:

```
contract TestContract {
    function test() external {
        address[] memory z = new address[](0);
    }
}
```

### Version:

0.9.3

### Relevant log output:

```
Contract TestContract
        Function TestContract.test() (*)
                Expression: z = new address[](0)
                IRs:
                        TMP_7 = new address[](0)
                        z(address[]) := TMP_7 (address[])(address[])
```
The type of TMP_7 doesn't show up here, but if we modify the `__str__` method of the `TemporaryVariable` class then we see that it's `address`.

**Comment by 0xalpharush** [comment] 2023-05-12 19:24
I believe this is a duplicate of https://github.com/crytic/slither/issues/1776 which has a fix pending review

**Comment by kevinclancy** [comment] 2023-05-12 19:26
Oh, oops. You're right. Looks like I already noticed that issue and gave it a thumbs up.

**Comment by 0xalpharush** [comment] 2023-05-12 19:30
No worries, appreciate the bug reports!

**Closed** 2023-05-12 19:30 UTC
Labels: duplicate
