### ISSUE TITLE
AttributeError: 'NoneType' object has no attribute 'storage_size'

### ISSUE THREAD

**Issue by rmi7** [crytic/slither#1004] opened 2021-12-16 00:09 UTC
`slither --version` == 0.8.2

Command:

`slither 0x08379aa73d43840f1658e062dc5e16114838882a`

Output:

```
Variable not found: TOKEN_NAME (context MetaInu)
Variable not found: TOKEN_SYMBOL (context MetaInu)
Variable not found: DECIMALS (context MetaInu)
Missing state variable Variable not found: TOTAL_SUPPLY (context MetaInu)
Missing function Variable not found: INITIAL_TAX (context MetaInu)
Traceback (most recent call last):
  File "/Users/me/slither/slither/__main__.py", line 743, in main_impl
    ) = process_all(filename, args, detector_classes, printer_classes)
  File "/Users/me/slither/slither/__main__.py", line 84, in process_all
    ) = process_single(compilation, args, detector_classes, printer_classes)
  File "/Users/me/slither/slither/__main__.py", line 67, in process_single
    slither = Slither(target, ast_format=ast, **vars(args))
  File "/Users/me/slither/slither/slither.py", line 125, in __init__
    parser.analyze_contracts()
  File "/Users/me/slither/slither/solc_parsing/slither_compilation_unit_solc.py", line 445, in analyze_contracts
    self._compilation_unit.compute_storage_layout()
  File "/Users/me/slither/slither/core/compilation_unit.py", line 257, in compute_storage_layout
    size, new_slot = var.type.storage_size
AttributeError: 'NoneType' object has no attribute 'storage_size'
None
Error in 0x08379aa73d43840f1658e062dc5e16114838882a
Traceback (most recent call last):
  File "/Users/me/slither/slither/__main__.py", line 743, in main_impl
    ) = process_all(filename, args, detector_classes, printer_classes)
  File "/Users/me/slither/slither/__main__.py", line 84, in process_all
    ) = process_single(compilation, args, detector_classes, printer_classes)
  File "/Users/me/slither/slither/__main__.py", line 67, in process_single
    slither = Slither(target, ast_format=ast, **vars(args))
  File "/Users/me/slither/slither/slither.py", line 125, in __init__
    parser.analyze_contracts()
  File "/Users/me/slither/slither/solc_parsing/slither_compilation_unit_solc.py", line 445, in analyze_contracts
    self._compilation_unit.compute_storage_layout()
  File "/Users/me/slither/slither/core/compilation_unit.py", line 257, in compute_storage_layout
    size, new_slot = var.type.storage_size
AttributeError: 'NoneType' object has no attribute 'storage_size'
```

**Comment by 0xalpharush** [comment] 2021-12-28 16:44
@montyly, this is section of code is throwing an error and preventing all of the state variables from being assigned types. Thus, the type is `NoneType`. It seems that some of the constant variables on the contract are not being parse correctly:
```

```
    def analyze_state_variables(self):
        for var_parser in self._variables_parser:
            try:
                var_parser.analyze(self)
            except (VariableNotFound, KeyError) as e:
                self.log_incorrect_parsing(f"Missing state variable {e}")
        return
```

**Comment by montyly** [comment] 2022-01-03 08:19
Thanks  @0xalpharush for tracking the issue. It might be a duplicate of https://github.com/crytic/slither/issues/995

**Comment by 0xalpharush** [comment] 2022-08-05 13:59
This works on latest master, ce9dbf650d7acfee51ddafd844929f4e8d345672.

**Closed by 0xalpharush** 2022-08-05 13:59 UTC
Labels: bug
