### ISSUE TITLE
[Bug]: node.scope.is_checked

### ISSUE THREAD

**Issue by MollyHe5** [crytic/slither#1864] opened 2023-04-25 02:33 UTC
### Describe the issue:

It seems that the node.scope.is_checked values of if statements inside the unchecked block are not accurate.
In the following example, node.scope.is_checked of ```result += 1``` in function ```test1``` returns ```True```, node.scope.is_checked of ```result += 2``` in function ```test1``` returns ```False```, node.scope.is_checked of ```result += 1``` in function ```test2``` returns ```False``` and node.scope.is_checked of ```result += 2``` in function ```test2``` returns ```False```. But the node.scope.is_checked value of these 4 nodes should all be false. 

### Code example to reproduce the issue:
```
function test1(uint256 value) internal pure returns (uint256) {
        uint256 result = 0;
        unchecked {
            if (value > 0) {
                result += 1;
            }
            result += 2;
        }
        return result;
    }

function test2(uint256 value) internal pure returns (uint256) {
        uint256 result = 0;
        unchecked {
            result += 2;
            if (value > 0) {
                result += 1;
            }
        }
        return result;
    }
```
### Version:

0.9.1

**Comment by smonicas** [comment] 2023-04-25 08:54
This is a duplicate of #1187

**Comment by 0xalpharush** [comment] 2023-06-06 18:08
Tracking in #1187

**Closed by 0xalpharush** 2023-06-06 18:08 UTC
Labels: bug, duplicate
