### ISSUE TITLE
Incorrect parsing of Try/Catch syntax

### ISSUE THREAD

**Issue by Thomas-Sciaroni** [crytic/slither#914] opened 2021-08-14 14:00 UTC
The detectors do not understand that the try block declares a variable, initializes it to the return value of the called function, and then makes it available in the try scope.
```
// SPDX-License-Identifier: unlicensed

pragma solidity ^0.8.0;

interface IContract {
    function foo() external returns (uint256);
}

contract Test {
    function test(address _contractAddress) external {
        IContract _contract = IContract(_contractAddress);
        try _contract.foo() returns (uint256 bar) {
            uint256 x = bar;
        } catch {
            revert("Contract does not implement foo()");
        }
    }
}
```

```
INFO:Detectors:
Test.test(address).bar (contracts/LiquidityOcean/Test.sol#12) is a local variable never initialized
Reference: https://github.com/crytic/slither/wiki/Detector-Documentation#uninitialized-local-variables
INFO:Detectors:
Test.test(address) (contracts/LiquidityOcean/Test.sol#10-17) ignores return value by _contract.foo() (contracts/LiquidityOcean/Test.sol#12-16)
Reference: https://github.com/crytic/slither/wiki/Detector-Documentation#unused-return
INFO:Detectors:
Variable 'Test.test(address).bar (contracts/LiquidityOcean/Test.sol#12)' in Test.test(address) (contracts/LiquidityOcean/Test.sol#10-17) potentially used before declaration: x = bar (contracts/LiquidityOcean/Test.sol#13)
Reference: https://github.com/crytic/slither/wiki/Detector-Documentation#pre-declaration-usage-of-local-variables
```

**Comment by montyly** [comment] 2021-08-16 07:53
I @Thomas-Sciaroni . Thank you for reporting this.

We are aware of the incorrect parsing of the try/catch syntax, and will improve it (related: https://github.com/crytic/slither/issues/511)

**Comment by 0xmichalis** [comment] 2023-03-05 14:17
Also duplicate of https://github.com/crytic/slither/issues/982

**Closed** 2024-03-22 22:48 UTC
Labels: bug, enhancement
