### ISSUE TITLE
[Bug] CONTINUE node to point to the increment EXPRESSION and not BEGINLOOP

### ISSUE THREAD

**Issue by 0xalpharush** [crytic/slither#1326] opened 2022-08-04 22:06 UTC
TBD: we might want the CONTINUE node to point to the increment EXPRESSION and not STARTLOOP. See visualization [here](https://dreampuf.github.io/GraphvizOnline/#digraph%7B%0A0%5Blabel%3D%22Node%20Type%3A%20ENTRY_POINT%200%0A%22%5D%3B%0A0-%3E3%3B%0A1%5Blabel%3D%22Node%20Type%3A%20BEGIN_LOOP%201%0A%22%5D%3B%0A1-%3E4%3B%0A2%5Blabel%3D%22Node%20Type%3A%20END_LOOP%202%0A%22%5D%3B%0A3%5Blabel%3D%22Node%20Type%3A%20NEW%20VARIABLE%203%0A%0AEXPRESSION%3A%0Ai%20%3D%200%0A%0AIRs%3A%0Ai(uint256)%20%3A%3D%200(uint256)%22%5D%3B%0A3-%3E1%3B%0A4%5Blabel%3D%22Node%20Type%3A%20IF_LOOP%204%0A%0AEXPRESSION%3A%0Ai%20%3C%2010%0A%0AIRs%3A%0ATMP_0(bool)%20%3D%20i%20%3C%2010%0ACONDITION%20TMP_0%22%5D%3B%0A4-%3E5%5Blabel%3D%22True%22%5D%3B%0A4-%3E2%5Blabel%3D%22False%22%5D%3B%0A5%5Blabel%3D%22Node%20Type%3A%20IF%205%0A%0AEXPRESSION%3A%0Ai%20%3E%20100%0A%0AIRs%3A%0ATMP_1(bool)%20%3D%20i%20%3E%20100%0ACONDITION%20TMP_1%22%5D%3B%0A5-%3E6%5Blabel%3D%22True%22%5D%3B%0A5-%3E7%5Blabel%3D%22False%22%5D%3B%0A6%5Blabel%3D%22Node%20Type%3A%20BREAK%206%0A%22%5D%3B%0A6-%3E2%3B%0A7%5Blabel%3D%22Node%20Type%3A%20END_IF%207%0A%22%5D%3B%0A7-%3E8%3B%0A8%5Blabel%3D%22Node%20Type%3A%20IF%208%0A%0AEXPRESSION%3A%0Ai%20%3C%203%0A%0AIRs%3A%0ATMP_2(bool)%20%3D%20i%20%3C%203%0ACONDITION%20TMP_2%22%5D%3B%0A8-%3E9%5Blabel%3D%22True%22%5D%3B%0A8-%3E10%5Blabel%3D%22False%22%5D%3B%0A9%5Blabel%3D%22Node%20Type%3A%20CONTINUE%209%0A%22%5D%3B%0A9-%3E1%3B%0A10%5Blabel%3D%22Node%20Type%3A%20END_IF%2010%0A%22%5D%3B%0A10-%3E13%3B%0A11%5Blabel%3D%22Node%20Type%3A%20BEGIN_LOOP%2011%0A%22%5D%3B%0A11-%3E14%3B%0A12%5Blabel%3D%22Node%20Type%3A%20END_LOOP%2012%0A%22%5D%3B%0A12-%3E23%3B%0A13%5Blabel%3D%22Node%20Type%3A%20NEW%20VARIABLE%2013%0A%0AEXPRESSION%3A%0Aj%20%3D%200%0A%0AIRs%3A%0Aj(uint256)%20%3A%3D%200(uint256)%22%5D%3B%0A13-%3E11%3B%0A14%5Blabel%3D%22Node%20Type%3A%20IF_LOOP%2014%0A%0AEXPRESSION%3A%0Aj%20%3C%2010%0A%0AIRs%3A%0ATMP_3(bool)%20%3D%20j%20%3C%2010%0ACONDITION%20TMP_3%22%5D%3B%0A14-%3E15%5Blabel%3D%22True%22%5D%3B%0A14-%3E12%5Blabel%3D%22False%22%5D%3B%0A15%5Blabel%3D%22Node%20Type%3A%20IF%2015%0A%0AEXPRESSION%3A%0Aj%20%3E%2010%0A%0AIRs%3A%0ATMP_4(bool)%20%3D%20j%20%3E%2010%0ACONDITION%20TMP_4%22%5D%3B%0A15-%3E16%5Blabel%3D%22True%22%5D%3B%0A15-%3E17%5Blabel%3D%22False%22%5D%3B%0A16%5Blabel%3D%22Node%20Type%3A%20CONTINUE%2016%0A%22%5D%3B%0A16-%3E11%3B%0A17%5Blabel%3D%22Node%20Type%3A%20END_IF%2017%0A%22%5D%3B%0A17-%3E18%3B%0A18%5Blabel%3D%22Node%20Type%3A%20IF%2018%0A%0AEXPRESSION%3A%0Aj%20%3C%203%0A%0AIRs%3A%0ATMP_5(bool)%20%3D%20j%20%3C%203%0ACONDITION%20TMP_5%22%5D%3B%0A18-%3E19%5Blabel%3D%22True%22%5D%3B%0A18-%3E20%5Blabel%3D%22False%22%5D%3B%0A19%5Blabel%3D%22Node%20Type%3A%20BREAK%2019%0A%22%5D%3B%0A19-%3E12%3B%0A20%5Blabel%3D%22Node%20Type%3A%20END_IF%2020%0A%22%5D%3B%0A20-%3E21%3B%0A21%5Blabel%3D%22Node%20Type%3A%20EXPRESSION%2021%0A%0AEXPRESSION%3A%0Aj%20-%3D%201%0A%0AIRs%3A%0Aj(uint256)%20%3D%20j%20(c)-%201%22%5D%3B%0A21-%3E22%3B%0A22%5Blabel%3D%22Node%20Type%3A%20EXPRESSION%2022%0A%0AEXPRESSION%3A%0Aj%20%2B%2B%0A%0AIRs%3A%0ATMP_6(uint256)%20%3A%3D%20j(uint256)%0Aj(uint256)%20%3D%20j%20(c)%2B%201%22%5D%3B%0A22-%3E14%3B%0A23%5Blabel%3D%22Node%20Type%3A%20EXPRESSION%2023%0A%0AEXPRESSION%3A%0Ai%20%2B%2B%0A%0AIRs%3A%0ATMP_7(uint256)%20%3A%3D%20i(uint256)%0Ai(uint256)%20%3D%20i%20(c)%2B%201%22%5D%3B%0A23-%3E4%3B%0A%7D%0A). Will open an issue and fix in a follow-on PR

_Originally posted by @0xalpharush in https://github.com/crytic/slither/issues/629#issuecomment-1205565862_

**Comment by plotchy** [comment] 2022-08-09 13:24
Currently this means that walking along node sons - typically used in `explore()` fns - would not accurately have `continue` statements with an increment block amongst its sons. Could lead to inaccurate tainting or visitor logic.

Looks like a good change to me 👍️

**Comment by plotchy** [comment] 2022-10-17 15:55
Adding to this discussion, a detector I made for "unreachable code" does flag on this difference with `continue` not being succeeded by the `increment` expression.
```python
def _detect(self):  # pylint: disable=too-many-locals,too-many-branches
        results = []

        # Loop through all contracts
        for contract in self.contracts:

            # Next we'll want to loop through all functions defined directly in this contract.
            # need to remove slitherConstructorConstantVariables & slitherConstructorVariables from the list of functions.
            # property f.is_constructor_variables returns a bool directly for this
            functions = [function for function in contract.functions_declared if not function.is_constructor_variables]

            for function in functions:
                func_nodes = function.nodes

                reachable_nodes = set()
                for node in func_nodes:
                    for r_node in reachable(node):
                        reachable_nodes.add(r_node)
                unreachable_nodes = set(func_nodes) - reachable_nodes
                for unreachable_node in unreachable_nodes:
                    if unreachable_node.type != NodeType.ENTRYPOINT:
                        # ENTRYPOINT nodes are false positives, as they cannot be reached inside the fn
                        info = [function, f" Has unreachable code at this node:\n", unreachable_node, "\n"]
                        res = self.generate_result(info)
                        results.append(res)

        return results 
```

While detecting on Notional deployed contract https://etherscan.io/address/0x5f11e94e0a69ac8490f45eb27a6478dcddb0227e#code

```js
function _mergeAssetIntoArray(
        PortfolioAsset[] memory assetArray,
        uint256 currencyId,
        uint256 maturity,
        uint256 assetType,
        int256 notional
    ) private pure returns (bool) {
        for (uint256 i = 0; i < assetArray.length; i++) {
            PortfolioAsset memory asset = assetArray[i];
            if (
                asset.assetType != assetType ||
                asset.currencyId != currencyId ||
                asset.maturity != maturity
            ) continue;

            // Either of these storage states mean that some error in logic has occurred, we cannot
            // store this portfolio
            require(
                asset.storageState != AssetStorageState.Delete &&
                asset.storageState != AssetStorageState.RevertIfStored
            ); // dev: portfolio handler deleted storage

            int256 newNotional = asset.notional.add(notional);
            // Liquidity tokens cannot be reduced below zero.
            if (AssetHandler.isLiquidityToken(assetType)) {
                require(newNotional >= 0); // dev: portfolio handler negative liquidity token balance
            }

            require(newNotional >= type(int88).min && newNotional <= type(int88).max); // dev: portfolio handler notional overflow

            asset.notional = newNotional;
            asset.storageState = AssetStorageState.Update;

            return true;
        }

        return false;
    }
```
The `i++` is unreachable, although there is a `continue` statement

**Comment by duckki** [comment] 2023-02-09 18:00
This is a duplicate of https://github.com/crytic/slither/issues/435.

**Comment by Tiko7454** [comment] 2023-07-06 14:05
To me continue must always point to the `IF_LOOP`, because it will work for every type of loop, not only `for` but also `while`. Also that will fix the inconsistency. Here is an example

```solidity
contract C {
  function f() public {
    int x  = 2;
    while (x < 100) {
      x++;
      if (x > 10) {
        continue;
      }
      x += 12;
  }
}
```
Here, `x += 12` points to `IF_LOOP`, but continue points to `BEGIN_LOOP`. Due to that inconsistency, if someone wanted to run a loop analysis, he will find out two loops, one containing BEGIN_LOOP and the loop itself, the other the nodes, with ids 3, 4, 5, 7 and 8, which is false positive. Changing `continue` to point to `IF_LOOP` solves the issue. Here is the cfg.
```dot
digraph{
0[label="Node Type: ENTRY_POINT 0
"];
0->1;
1[label="Node Type: NEW VARIABLE 1

EXPRESSION:
x = 2

IRs:
x(int256) := 2(int256)"];
1->2;
2[label="Node Type: BEGIN_LOOP 2
"];
2->3;
3[label="Node Type: IF_LOOP 3

EXPRESSION:
x < 100

IRs:
TMP_0(bool) = x < 100
CONDITION TMP_0"];
3->4[label="True"];
3->9[label="False"];
4[label="Node Type: EXPRESSION 4

EXPRESSION:
x ++

IRs:
TMP_1(int256) := x(int256)
x(int256) = x (c)+ 1"];
4->5;
5[label="Node Type: IF 5

EXPRESSION:
x > 10

IRs:
TMP_2(bool) = x > 10
CONDITION TMP_2"];
5->6[label="True"];
5->7[label="False"];
6[label="Node Type: CONTINUE 6
"];
6->2;
7[label="Node Type: END_IF 7
"];
7->8;
8[label="Node Type: EXPRESSION 8

EXPRESSION:
x += 12

IRs:
x(int256) = x (c)+ 12"];
8->3;
9[label="Node Type: END_LOOP 9
"];
}
```

**Comment by 0xalpharush** [comment] 2023-07-06 14:18
We will eventually have some sort of lowering context that stores the current continue destination and it doesn't have to be the same for the various loop constructs rather just correct. The current CFG code serially parses the AST and doesn't have the ability to look ahead and add the proper destination node because it hasn't yet been created sometimes

**Closed** 2024-03-01 22:27 UTC
Labels: bug, cfg
