### ISSUE TITLE
Increase granularity dataflow analysis

### ISSUE THREAD

**Issue by JoranHonig** [crytic/slither#2313] opened 2024-02-19 14:21 UTC
### Describe the desired feature

I was playing around with slither and trying to write an analysis module to do the following:

1. find all modifier implementations
2. in each modifier find each equivalence comparison and mark them
3. find all execution paths where a marked variable remains unchecked

```
modifier example {
        bool intermediate = msg.sender == owner; // should not trigger here
        require(intermediate);
}
```

However, the problem seems to be as follows:

Statement 1's IR statements roughly looks like this:
tmp_0 = comparison
intermediate = tmp_0

Unfortunately, I believe the available dataflow libraries do not allow me to then check whether the local variable in the require statement depends on the temporary variable in the IR expansion of the earlier statement.

Lmk if I'm missing something here 🙏 .

**Comment by 0xalpharush** [comment] 2024-02-19 18:02
This looks like a regression caused by https://github.com/crytic/slither/pull/1984 which should be fixed by https://github.com/crytic/slither/pull/2201. The SSA IR was not being created correctly due to the `is_reachable` property not being set (this affects the dominator calculation and thus SSA generation). We should have caught this in testing so I will make sure a data dependency and SSA IR for modifiers is running in CI

cc @Tiko7454

**Closed** 2024-02-20 17:56 UTC
Labels: enhancement
