### ISSUE TITLE
[Bug-Candidate]: Cannot run `slither` in a hardhat project.

### ISSUE THREAD

**Issue by hickscorp** [crytic/slither#1241] opened 2022-06-16 17:40 UTC
### Describe the issue:

In a project with approximately 20 solidity files, it doesn't seem possible to run `slither`. I've tried many options to no avail.
Just in case this helps - running `slither` on individual solidity files works, but generates lots of fake positives - because it lacks context of all other tokens from files it doesn't see, probably.

### Code example to reproduce the issue:

It would be very difficult to pinpoint which solidity file is problematic (if any) as the project has more than one solidity file. It is however possible to clone the repo on github at `tableturn/tt-white-contracts` (make sure to use the `integrates-with-hardhat-deploy` branch).

### Version:

0.8.3

### Relevant log output:

```shell
'npx hardhat compile --force' running
Generating typings for: 31 artifacts in dir: typechain for target: ethers-v5
Successfully generated 60 typings!
Compiled 31 Solidity files successfully

Traceback (most recent call last):
  File "/home/user/.local/lib/python3.9/site-packages/slither/__main__.py", line 744, in main_impl
    ) = process_all(filename, args, detector_classes, printer_classes)
  File "/home/user/.local/lib/python3.9/site-packages/slither/__main__.py", line 87, in process_all
    ) = process_single(compilation, args, detector_classes, printer_classes)
  File "/home/user/.local/lib/python3.9/site-packages/slither/__main__.py", line 70, in process_single
    slither = Slither(target, ast_format=ast, **vars(args))
  File "/home/user/.local/lib/python3.9/site-packages/slither/slither.py", line 95, in __init__
    parser.parse_top_level_from_loaded_json(ast, path)
  File "/home/user/.local/lib/python3.9/site-packages/slither/solc_parsing/slither_compilation_unit_solc.py", line 211, in parse_top_level_from_loaded_json
    contract.set_offset(top_level_data["src"], self._compilation_unit)
  File "/home/user/.local/lib/python3.9/site-packages/slither/core/source_mapping/source_mapping.py", line 124, in set_offset
    self._source_mapping = self._convert_source_mapping(offset, compilation_unit)
  File "/home/user/.local/lib/python3.9/site-packages/slither/core/source_mapping/source_mapping.py", line 101, in _convert_source_mapping
    (lines, starting_column, ending_column) = self._compute_line(
  File "/home/user/.local/lib/python3.9/site-packages/slither/core/source_mapping/source_mapping.py", line 43, in _compute_line
    end_line, ending_column = compilation_unit.core.crytic_compile.get_line_from_offset(
  File "/home/user/.local/lib/python3.9/site-packages/crytic_compile/crytic_compile.py", line 291, in get_line_from_offset
    return lines_delimiters[offset]
KeyError: 6870
None
Error in .
Traceback (most recent call last):
  File "/home/user/.local/lib/python3.9/site-packages/slither/__main__.py", line 744, in main_impl
    ) = process_all(filename, args, detector_classes, printer_classes)
  File "/home/user/.local/lib/python3.9/site-packages/slither/__main__.py", line 87, in process_all
    ) = process_single(compilation, args, detector_classes, printer_classes)
  File "/home/user/.local/lib/python3.9/site-packages/slither/__main__.py", line 70, in process_single
    slither = Slither(target, ast_format=ast, **vars(args))
  File "/home/user/.local/lib/python3.9/site-packages/slither/slither.py", line 95, in __init__
    parser.parse_top_level_from_loaded_json(ast, path)
  File "/home/user/.local/lib/python3.9/site-packages/slither/solc_parsing/slither_compilation_unit_solc.py", line 211, in parse_top_level_from_loaded_json
    contract.set_offset(top_level_data["src"], self._compilation_unit)
  File "/home/user/.local/lib/python3.9/site-packages/slither/core/source_mapping/source_mapping.py", line 124, in set_offset
    self._source_mapping = self._convert_source_mapping(offset, compilation_unit)
  File "/home/user/.local/lib/python3.9/site-packages/slither/core/source_mapping/source_mapping.py", line 101, in _convert_source_mapping
    (lines, starting_column, ending_column) = self._compute_line(
  File "/home/user/.local/lib/python3.9/site-packages/slither/core/source_mapping/source_mapping.py", line 43, in _compute_line
    end_line, ending_column = compilation_unit.core.crytic_compile.get_line_from_offset(
  File "/home/user/.local/lib/python3.9/site-packages/crytic_compile/crytic_compile.py", line 291, in get_line_from_offset
    return lines_delimiters[offset]
KeyError: 6870
```

**Comment by 0xalpharush** [comment] 2022-06-16 17:48
duplicate of #1240

**Closed** 2022-06-22 01:32 UTC
Labels: duplicate, bug-candidate
